#!/usr/bin/env python3
"""
post-approve hook - runs after pm-approve completes.

1. Render companion HTML for stages 04 and 05.
2. Cascade staleness: downstream approved stages -> stale.
3. Push telemetry + feedback JSONL to feedback repo.
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "lib"))

from project import resolve_project, load_meta, save_meta, get_stage, artifact_path, downstream_stage_ids
from frontmatter import update_status
from html_render import render_design_spec, render_prototype_mockup
from telemetry import log
from git_sync import push_feedback_repo


def main():
    stage_id = os.environ.get("PM_OS_STAGE")
    if not stage_id:
        sys.exit(0)

    try:
        project_root = resolve_project()
    except FileNotFoundError as e:
        print(f"[post-approve] ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    meta = load_meta(project_root)

    # --- Render companion HTML for stages with generated previews ---
    try:
        if stage_id == "04":
            output_path = render_design_spec(project_root)
            print(f"[post-approve] Rendered companion HTML: {output_path.name}")
        elif stage_id == "05":
            mockup_path = project_root / "05-prototype-mockup.html"
            if mockup_path.exists():
                print(f"[post-approve] Skipped HTML render: 05-prototype-mockup.html already present (generated by pm-prototype-html skill).")
            else:
                output_path = render_prototype_mockup(project_root)
                print(f"[post-approve] Rendered fallback companion HTML: {output_path.name}")
    except Exception as e:
        print(f"[post-approve] WARNING: Could not render companion HTML: {e}", file=sys.stderr)

    # --- Cascade staleness to downstream approved stages ---
    downstream_ids = downstream_stage_ids(stage_id, meta)

    stale_logged = []
    for did in downstream_ids:
        try:
            ds_meta = get_stage(meta, did)
        except KeyError:
            continue
        if ds_meta["status"] == "approved":
            ds_meta["status"] = "stale"
            apath = artifact_path(project_root, did)
            if apath.exists():
                update_status(str(apath), "stale")
            log("stage_marked_stale", project_root, did, {
                "reason": "upstream_approved",
                "triggering_upstream_stage": stage_id,
            })
            stale_logged.append(did)

    if stale_logged:
        save_meta(meta, project_root)
        print(f"[post-approve] Marked downstream stages stale: {', '.join(stale_logged)}")

    # --- Rebuild the traceability spine when an ID-bearing stage is approved ---
    # Stage 03 (PRD) declares requirement ids; stage 06 (QA plan) declares the
    # TC-### scenarios that link to them. Re-derive .traceability.yaml (a local,
    # derived index) so the resolver answers coverage queries without rescanning.
    if stage_id in {"03", "06"}:
        try:
            import traceability as trace
            index = trace.rebuild(project_root)
            reqs = len(index.get("requirements") or {})
            tcs = len(index.get("test_cases") or {})
            print(f"[post-approve] Rebuilt {trace.TRACEABILITY_FILENAME}: "
                  f"{reqs} requirement(s), {tcs} test case(s).")
            uncovered = trace.uncovered_requirements(project_root)
            if uncovered:
                print(f"[post-approve] Requirements with no covering scenario: "
                      f"{', '.join(uncovered)}")
        except Exception as e:
            print(f"[post-approve] WARNING: Could not rebuild traceability: {e}",
                  file=sys.stderr)

    # --- Push to feedback repo (report status clearly, never silently swallow) ---
    try:
        status = push_feedback_repo(project_root)
        if status.get("ok"):
            print(f"[post-approve] Central sync: {status.get('reason')}.")
        else:
            print(f"[post-approve] Central sync FAILED — {status.get('reason')}. "
                  f"Retry with /pm-sync.", file=sys.stderr)
    except Exception as e:
        print(f"[post-approve] WARNING: Could not push to feedback repo: {e}", file=sys.stderr)

    sys.exit(0)


if __name__ == "__main__":
    main()
